-- noinspection SqlNoDataSourceInspectionForFile

-- ------------------------- --
-- SETUP BASE INFRASTRUCTURE --
-- ------------------------- --
USE ROLE ACCOUNTADMIN;

-- Admin user
CREATE OR REPLACE ROLE LAB_ADMIN;
GRANT ROLE LAB_ADMIN TO ROLE SYSADMIN;
-- Participant user
CREATE OR REPLACE ROLE LAB_USER;
GRANT ROLE LAB_USER TO ROLE LAB_ADMIN;

-- Databases
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS CHAT_WITH_YOUR_DATA;
DROP SCHEMA IF EXISTS CHAT_WITH_YOUR_DATA.PUBLIC;
GRANT ALL PRIVILEGES ON DATABASE CHAT_WITH_YOUR_DATA TO ROLE LAB_ADMIN;
GRANT USAGE ON DATABASE CHAT_WITH_YOUR_DATA TO ROLE LAB_USER;

-- Warehouses
CREATE OR REPLACE WAREHOUSE LAB_ADMIN_WAREHOUSE WITH
    INITIALLY_SUSPENDED = TRUE
-- WAREHOUSE_SIZE = 'LARGE'
-- WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED'
;
GRANT USAGE ON WAREHOUSE LAB_ADMIN_WAREHOUSE TO ROLE LAB_ADMIN;

CREATE OR REPLACE WAREHOUSE LAB_USER_WAREHOUSE WITH
    INITIALLY_SUSPENDED = TRUE
-- WAREHOUSE_SIZE = 'LARGE'
-- WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED'
-- MAX_CLUSTER_COUNT = 10
;

-- Admin schema
USE ROLE LAB_ADMIN;
CREATE SCHEMA IF NOT EXISTS CHAT_WITH_YOUR_DATA.WORKSPACE_0;
USE ROLE SYSADMIN;
