-- noinspection SqlNoDataSourceInspectionForFile

-- ------------------------- --
-- SETUP BASE INFRASTRUCTURE --
-- ------------------------- --
USE ROLE ACCOUNTADMIN;

-- Admin user
CREATE OR REPLACE ROLE HOL_ADMIN;
GRANT ROLE HOL_ADMIN TO ROLE SYSADMIN;
-- Participant user
CREATE OR REPLACE ROLE HOL_USER;
GRANT ROLE HOL_USER TO ROLE HOL_ADMIN;

-- Databases
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS CHAT_WITH_YOUR_DATA;
DROP SCHEMA IF EXISTS CHAT_WITH_YOUR_DATA.PUBLIC;
GRANT ALL PRIVILEGES ON DATABASE CHAT_WITH_YOUR_DATA TO ROLE HOL_ADMIN;
GRANT USAGE ON DATABASE CHAT_WITH_YOUR_DATA TO ROLE HOL_USER;

-- Warehouses
CREATE OR REPLACE WAREHOUSE HOL_ADMIN_WAREHOUSE WITH
    INITIALLY_SUSPENDED = TRUE
-- WAREHOUSE_SIZE = 'LARGE'
-- WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED'
;
GRANT USAGE ON WAREHOUSE HOL_ADMIN_WAREHOUSE TO ROLE HOL_ADMIN;

CREATE OR REPLACE WAREHOUSE HOL_USER_WAREHOUSE WITH
    INITIALLY_SUSPENDED = TRUE
-- WAREHOUSE_SIZE = 'LARGE'
-- WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED'
-- MAX_CLUSTER_COUNT = 10
;

-- Admin schema
USE ROLE HOL_ADMIN;
CREATE SCHEMA IF NOT EXISTS CHAT_WITH_YOUR_DATA.WORKSPACE_0;
