-- ------------------------- --
-- SETUP BASE INFRASTRUCTURE --
-- ------------------------- --
USE ROLE ACCOUNTADMIN;

-- Admin user
CREATE ROLE HOL_ADMIN;
GRANT ROLE HOL_ADMIN TO ROLE SYSADMIN;
-- Participant user
CREATE ROLE HOL_USER;
GRANT ROLE HOL_USER TO ROLE HOL_ADMIN;

-- Databases
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS HOL_ADMIN_DB;
GRANT ALL PRIVILEGES ON DATABASE HOL_ADMIN_DB TO ROLE HOL_ADMIN;
CREATE DATABASE HOL_USER_DB;
GRANT ALL PRIVILEGES ON DATABASE HOL_USER_DB TO ROLE HOL_ADMIN;

-- Warehouses
CREATE WAREHOUSE HOL_ADMIN_WAREHOUSE;
GRANT USAGE ON WAREHOUSE HOL_ADMIN_WAREHOUSE TO ROLE HOL_ADMIN;
CREATE WAREHOUSE HOL_USER_WAREHOUSE;
GRANT USAGE ON WAREHOUSE HOL_USER_WAREHOUSE TO ROLE HOL_ADMIN;
